### PR TITLE
Added first test case for IP

### PR DESCRIPTION
**Pull request by JoshUoM**
Image Processing (IP) test case No.1.

Tested out a way to segment grains into separate entities and estimate their average diameter. The image used was taken from Materials Science and Engineering: an introduction, by Callister.

### CODE REVIEW

**Review by Gbowker — APPROVED** [review]
Looks good. Strange preview layout on here though

**Review by Sakina-1 — APPROVED** [review]
Looks good

**Comment by Gbowker** [comment]
Joooooshhh are you gonna merge it or whaaaaat?

**Comment by Gbowker** [comment]
Ive left a branch in FEM with a comment stream like this one that walks you through which merge to use. 👍

**Pull request merged**
