### PR TITLE
Added testcase V2.0 and sample image

### PR DESCRIPTION
**Pull request by JoshUoM**
A successful image processing test-case where I isolated the grains in a SA-508 Grade 3 steel microstructure  with known grain size. I then calculated the grain size from the processed image and obtained a similar value.

### CODE REVIEW

**Comment by Sakina-1** [comment]
Looks good, checked the image and code

**Comment by Gbowker** [comment]
Looks good, happy to merge it. Maybe grain size could be improved using a more accurate method than average size of assumed perfect circles. (5.)

**Comment by Gbowker** [comment]
Im just going to re-upload my tutorial code with the racoon without the pic.png to the test branch, so just hold up merging before then.

**Review by Gbowker — APPROVED** [review]
Made the changes to my code I first submitted in. You can go ahead and merge now.

**Review by Sakina-1 — APPROVED** [review]

**Pull request merged**
